# Tag
TAG_NAME_MAX_LENGTH = 200
TAG_SLUG_MAX_LENGTH = 200

# Ingredient
INGREDIENT_NAME_MAX_LENGTH = 200
MEASUREMENT_UNIT_MAX_LENGTH = 50

# Recipe
RECIPE_NAME_MAX_LENGTH = 200
COOKING_TIME_MIN = 1

# RecipeIngredient
INGREDIENT_AMOUNT_MIN = 1
INGREDIENT_AMOUNT_MAX = 10000

# CreateUserSerializer
NAME_MAX_LENGTH = 150
